### PR TITLE
Windows compatibility and UTF16 support on string MD5

### PR DESCRIPTION
**Pull request by orkblutt**
2 commits:
1- symbols exposing on Windows
2- Added md5_16 method to hash the UTF16 representation of a string

### CODE REVIEW

**Comment by moisseev** [comment]
I've tried to test `md5_16()` method like this:
```
# sqlite3 :memory:
SQLite version 3.21.0 2017-10-24 18:55:49
Enter ".help" for usage hints.
sqlite> .load ./libsqlitemd5.so
sqlite> select hex(md5(x'feff0061'));
4B936244FB81C0500598B1938266F69A
sqlite> select hex(md5_16(x'feff0061'));
F67048ADB95031C3FF71C13E7EA98F5F
sqlite> .q

# echo -n 'a' | iconv -f utf8 -t utf16 | md5 | tr "[a-z]" "[A-Z]"
4B936244FB81C0500598B1938266F69A
```
The `a` character is UTF16-encoded in all of the cases, right?
Why does its hash generated by `md5()` method match one generated by `md5` utility, and `md5_16()` method gives a different hash.
What am I missing here?

**Comment by orkblutt** [comment]
Hi,

don't forgot Endianness:
```
echo -n 'a' | iconv -f utf8 -t utf16le | od -t x1
0000000 61 00

echo -n 'a' | iconv -f utf8 -t utf16le | md5sum
4144e195f46de78a3623da7364d04f11

sqlite> select hex(md5_16(x'61')); // 'a'
4144E195F46DE78A3623DA7364D04F11

```



"sqlite3_value_text16" → | UTF-16 TEXT value in the native byteorder

We could fix the choice by using sqlite3_value_text16le or be variants.

Cheers

**Comment by moisseev** [comment]
Thank you for clarification. I forgot to switch encoding in sqlite.
With `pragma encoding = "UTF-16";` it works as expected.

Forgive my ignorance, but what benefits does `TEXT` have over `BLOB` from the point of view of hash computation? Why can't we use `BLOB` (the `md5()` method) for everything and don't care about encoding?

**Comment by orkblutt** [comment]
There is no real benefit. I needed, for my purpose, to convert utf8 ->utf16 strings before to md5 it inside a query. Maybe the sqliteshell is offering a way to convert utf8->utf16 directly ?
I was first tempted to write my own program using the lib but my lazyness drived me to google. Then I discovered the possibility to load plugins directly inside the shell by reading your code 👍 .

**Comment by moisseev** [comment]
The simplest approach is to set  "UTF-16" database encoding. 

```
# echo -n a | iconv -f utf8 -t utf16le | md5
4144e195f46de78a3623da7364d04f11

# sqlite3 :memory:
SQLite version 3.21.0 2017-10-24 18:55:49
Enter ".help" for usage hints.
sqlite> .load ./libsqlitemd5.so
sqlite> pragma encoding = "UTF-16";
sqlite> select hex(md5('a'));
4144E195F46DE78A3623DA7364D04F11
```

I have no objections to add your method as it is handy for some tasks. What if we change the method's name to `md5_utf16` ? It seems clearer to me. Would you add a description to the method?

**Comment by orkblutt** [comment]
yes md5_utf16 looks good.
We could describe it like that:
"Returns the md5 hash of a converted utf8 to utf6 encoded string"
Feel free to change it since my english isn't that good.

all the best

**Pull request closed without merging**
